// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AA4-A1-TASK2;

/************************************************************/
/**
 * 
 */
public class Bank {
	/**
	 * 
	 */
	public ResourceStack[] supply;

	/**
	 * 
	 * @param type  
	 * @param amount 
	 * @return 
	 */
	public boolean hasEnoughResources(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void distributeResource(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void collectResource(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public int Operation1(ResourceType type) {
	}
}
