// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AA4-A1-TASK2;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	public void intitialize() {
	}

	/**
	 * 
	 * @param number 
	 * @return 
	 */
	public Tile[] getTilesForNumber(int number) {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public Node[] getAvailableSettlementNodes(Player player) {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public Edge[] getAvailableRoadEdges(Player player) {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public Node getUpgradeableNodes(Player player) {
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getAvailableSetupNodes() {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public int calculateLongestRoad(Player player) {
	}
}
