// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AA4-A1-TASK2;

/************************************************************/
/**
 * 
 */
public class Building {
	/**
	 * 
	 */
	private BuildingType type;

	/**
	 * 
	 * @return 
	 */
	public BuildingType getType() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getResourceMultiplier() {
	}
}
