// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AA4-A1-TASK2;

/************************************************************/
/**
 * 
 */
public class CatanGame {
	/**
	 * 
	 */
	private int currentRound;
	/**
	 * 
	 */
	public int longestRoadLength;
	/**
	 * 
	 */
	public Player longestRoadHolder;

	/**
	 * 
	 */
	public void play() {
	}

	/**
	 * 
	 */
	public void setupPhase() {
	}

	/**
	 * 
	 */
	public void executeRound() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void executeTurn(Player player) {
	}

	/**
	 * 
	 * @param diceRoll 
	 */
	public void distributeResources(int diceRoll) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean checkWinCondition() {
	}

	/**
	 * 
	 */
	public void updateLongestRoad() {
	}

	/**
	 * 
	 */
	public void printRoundSummary() {
	}
}
