// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AA4-A1-TASK2;

/************************************************************/
/**
 * 
 */
public class Configuration {
	/**
	 * 
	 */
	private int maxRounds;

	/**
	 * 
	 * @return 
	 */
	public int getMaxRounds() {
	}

	/**
	 * 
	 * @param filepath 
	 */
	public void load(String filepath) {
	}
}
