// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AA4-A1-TASK2;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}

	/**
	 * 
	 * @return 
	 */
	public Road getRoad() {
	}

	/**
	 * 
	 */
	public void getEndPoints() {
	}
}
