// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AA4-A1-TASK2;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;

	/**
	 * 
	 * @return 
	 */
	public Node[] getAdjacentNodes() {
	}

	/**
	 * 
	 * @return 
	 */
	public Edge[] getAdjacentEdge() {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile[] getAdjacentTiles() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean satisfiesDistanceRule() {
	}

	/**
	 * 
	 * @return 
	 */
	public Building getBuilding() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}
}
