// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AA4-A1-TASK2;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceStack[] resources;
	/**
	 * 
	 */
	private int remainingSettlements;
	/**
	 * 
	 */
	private int remainingCities;
	/**
	 * 
	 */
	private int remainingRoads;

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getTotalResourceCards() {
	}

	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public int getResourceCount(ResourceType type) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void addResource(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void removeResource(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canBuildRoads() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canBuildCity() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canBuildSettlement() {
	}
}
