// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AA4-A1-TASK2;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private int numberToken;
	/**
	 * 
	 */
	private ResourceType resourceType;

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getToken() {
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceType getResourceType() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getAdjacentNodes() {
	}
}
